name: .NET

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Update
      run: sudo apt-get update
      
    - name: Install FFmpeg and FFprobe
      run: sudo apt-get install -y ffmpeg


    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
